# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'here & there' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for here & there
    pod 'Alamofire'
    pod 'RxAlamofire'
    pod 'RxSwift'
    pod 'RxGesture'
    pod 'RxDataSources'
    
    pod 'Kingfisher', '~> 5.0'

    pod 'SwiftLint', '~> 0.27.0'

    pod 'SwiftyJSON'
    pod 'IQKeyboardManagerSwift'
    pod 'SVProgressHUD'
    pod 'lottie-ios'
    
#    # Pods for Crashlytics.
#    pod 'Fabric'
#    pod 'Crashlytics'

end
